services:
  ndc-php-micro:
    image: kiviev/php-fpm:dev8.4
    container_name: php-fpm
    restart: always
    ports:
      - '9203:9003'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ../app:/var/www/app
      - ./build/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./build/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./build/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    command: ["php-fpm", "-F", "-R"]
    networks:
      service_network:

  ndc-nginx-micro:
    image: kiviev/nginx:1.27.4
    container_name: nginx
    restart: always
    ports:
      - '25080:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FPM_CONTAINER_NAME=php-fpm
    env_file:
      - .env
    depends_on:
      - ndc-php-micro
    volumes:
      - ../app:/var/www/app
    networks:
      service_network:

networks:
  service_network: